# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'my-card-holder' do
  use_frameworks!

  pod 'RealmSwift'
  pod 'PayCardsRecognizer'
  pod 'SwiftyJSON', '~> 4.0'

end
